"""
Chunked Transcript Translation (speaker-aware)
==================================================
backend/app/services/meeting_pipeline/translate/chunked_translate.py

Problem: a local translation model has a limited MAX OUTPUT TOKENS per
call, so a full meeting transcript can't be translated in one shot. It has
to be split into chunks and translated across multiple calls, while
keeping:

  1. TERMINOLOGY / CONTINUITY across chunk boundaries — handled via a
     bounded "translation memory" (running glossary + last few translated
     sentence pairs) carried forward each call, instead of a lossy
     summary. See TranslationMemory below.

  2. SPEAKER INTEGRITY across chunk boundaries — a chunk boundary should
     fall BETWEEN speaker turns, not in the middle of one person's
     continuous speech. If a single speaker's turn is itself longer than
     the whole token budget (rare — a long monologue), the split is
     unavoidable, but the next chunk is told explicitly "this continues
     SPEAKER_X's turn from before" so the model doesn't treat it as a
     fresh, unrelated line from an unknown speaker, and tone/register
     stays consistent with that speaker specifically (not just the
     transcript in general).

Segments are translated via the same numbered-list technique as
punctuate.py (1:1 input/output line correspondence, speaker shown per
line for the model's context but NOT re-generated by the model — we
already know the speaker from our own data, so it's never at risk of
being echoed back wrong).
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field, replace
from typing import Callable, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

MEMORY_START, MEMORY_END = "[MEMORY]", "[/MEMORY]"
SOURCE_START, SOURCE_END = "[SOURCE]", "[/SOURCE]"
TRANSLATION_START, TRANSLATION_END = "[TRANSLATION]", "[/TRANSLATION]"
GLOSSARY_START, GLOSSARY_END = "[GLOSSARY_UPDATES]", "[/GLOSSARY_UPDATES]"


# ---------------------------------------------------------------------------
# Input shape — speaker-attributed transcript segment (output of the
# aligner/matcher stages earlier in the pipeline)
# ---------------------------------------------------------------------------
@dataclass
class SpeakerTranscriptSegment:
    start: float
    end: float
    text: str
    speaker: str


# ---------------------------------------------------------------------------
# Translation memory — the bounded carry-over state between chunk calls
# ---------------------------------------------------------------------------
@dataclass
class TranslationMemory:
    glossary: Dict[str, str] = field(default_factory=dict)               # entities + terminology merged
    conversation_context: str = ""                                        # what's currently being discussed
    translation_rules: List[str] = field(default_factory=list)            # persistent style/policy rules
    # (speaker, source, translated) — speaker kept so recent-context lines
    # show WHO said what, not just floating text
    recent_pairs: List[Tuple[str, str, str]] = field(default_factory=list)
    max_recent_pairs: int = 6
    last_speaker: Optional[str] = None  # who was speaking at the end of the last chunk

    def update(
        self,
        new_glossary_entries: Dict[str, str],
        new_pairs: List[Tuple[str, str, str]],
        new_context: Optional[str] = None,
    ) -> None:
        self.glossary.update(new_glossary_entries)
        self.recent_pairs.extend(new_pairs)
        self.recent_pairs = self.recent_pairs[-self.max_recent_pairs:]
        if new_pairs:
            self.last_speaker = new_pairs[-1][0]
        if new_context:
            self.conversation_context = new_context  # replaced, not accumulated — stays 1 line

    def as_prompt_block(self, next_chunk_first_speaker: str, is_mid_turn_split: bool) -> str:
        lines = [MEMORY_START]

        if not self.glossary and not self.recent_pairs and not self.conversation_context:
            lines.append("(none yet — this is the first chunk)")
        else:
            if self.conversation_context:
                lines.append(f"current topic: {self.conversation_context}")
            if self.translation_rules:
                lines.append("standing rules (apply to every chunk):")
                for rule in self.translation_rules:
                    lines.append(f"- {rule}")
            if self.glossary:
                lines.append("glossary (keep these translations consistent):")
                for src, tgt in self.glossary.items():
                    lines.append(f"{src} = {tgt}")
            if self.recent_pairs:
                lines.append("recent sentences (for continuity — do not re-translate these):")
                for spk, src, tgt in self.recent_pairs:
                    lines.append(f"[{spk}] src: {src} | tgt: {tgt}")

        if is_mid_turn_split and next_chunk_first_speaker == self.last_speaker:
            lines.append(
                f"NOTE: this chunk continues {next_chunk_first_speaker}'s turn from the "
                f"previous chunk mid-sentence/mid-thought (not a new turn, no natural break "
                f"happened here) — keep the exact same tone and register as their most recent "
                f"lines above, as if translating one continuous utterance."
            )

        lines.append(MEMORY_END)
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Speaker-turn grouping + chunking
# ---------------------------------------------------------------------------
def estimate_tokens(text: str, chars_per_token: float = 4.0) -> int:
    """Rough token estimate. Pass your local model's real tokenizer via
    `token_estimator=` for an accurate budget instead."""
    return max(1, int(len(text) / chars_per_token))


def _group_into_turns(
    segments: List[SpeakerTranscriptSegment],
) -> List[Tuple[str, List[SpeakerTranscriptSegment]]]:
    """Consecutive same-speaker segments become one 'turn' — the unit
    chunking tries not to split."""
    turns: List[Tuple[str, List[SpeakerTranscriptSegment]]] = []
    current: List[SpeakerTranscriptSegment] = []
    current_speaker: Optional[str] = None

    for seg in segments:
        if current and seg.speaker != current_speaker:
            turns.append((current_speaker, current))
            current = []
        current.append(seg)
        current_speaker = seg.speaker

    if current:
        turns.append((current_speaker, current))
    return turns


def chunk_segments(
    segments: List[SpeakerTranscriptSegment],
    max_input_tokens: int,
    token_estimator: Callable[[str], int] = estimate_tokens,
) -> List[List[SpeakerTranscriptSegment]]:
    """
    Packs segments into chunks under max_input_tokens, preferring to break
    BETWEEN speaker turns rather than inside one. Only splits mid-turn if
    a single turn alone exceeds the whole budget (long monologue) — in
    that rare case it splits on segment boundaries within the turn, which
    still keeps sentence-level (segment-level) integrity, just not the
    whole turn in one chunk.
    """
    turns = _group_into_turns(segments)
    chunks: List[List[SpeakerTranscriptSegment]] = []
    current_chunk: List[SpeakerTranscriptSegment] = []
    current_tokens = 0

    def flush():
        nonlocal current_chunk, current_tokens
        if current_chunk:
            chunks.append(current_chunk)
            current_chunk, current_tokens = [], 0

    for _speaker, turn_segments in turns:
        turn_tokens = sum(token_estimator(s.text) for s in turn_segments)

        if turn_tokens > max_input_tokens:
            # Single turn bigger than the whole budget — unavoidable
            # mid-turn split. Flush whatever was pending first, then
            # split this turn on its own segment boundaries.
            flush()
            sub_chunk: List[SpeakerTranscriptSegment] = []
            sub_tokens = 0
            for seg in turn_segments:
                t = token_estimator(seg.text)
                if sub_chunk and sub_tokens + t > max_input_tokens:
                    chunks.append(sub_chunk)
                    sub_chunk, sub_tokens = [], 0
                sub_chunk.append(seg)
                sub_tokens += t
            if sub_chunk:
                chunks.append(sub_chunk)
            continue

        if current_chunk and current_tokens + turn_tokens > max_input_tokens:
            flush()

        current_chunk.extend(turn_segments)
        current_tokens += turn_tokens

    flush()
    return chunks


# ---------------------------------------------------------------------------
# Prompt building
# ---------------------------------------------------------------------------
# Prompt building
# ---------------------------------------------------------------------------
def build_prompt(
    chunk: List[SpeakerTranscriptSegment],
    memory: TranslationMemory,
    target_language: str,
) -> str:
    numbered_source = "\n".join(f"{i+1}. [{seg.speaker}] {seg.text}" for i, seg in enumerate(chunk))

    first_speaker = chunk[0].speaker
    is_mid_turn_split = memory.last_speaker is not None and first_speaker == memory.last_speaker
    memory_block = memory.as_prompt_block(first_speaker, is_mid_turn_split)

    glossary_hint = ""
    if memory.glossary:
        glossary_hint = f"\nGlossary to keep consistent:\n" + "\n".join(f"- {s} = {t}" for s, t in memory.glossary.items())

    return f"""Translate each numbered meeting transcript sentence into fluent {target_language}.
Translate any Hindi, Hinglish, or non-English speech into natural {target_language}.
Keep English sentences natural and clean.
Maintain technical terms (e.g. AWS, S3, PostgreSQL, Kafka, Redis, PR, Jira, K8s) intact.
Do NOT include speaker tags like [Satya] or [Subu] in your output.

{glossary_hint}

Here is the source transcript chunk:
{numbered_source}

Return EXACTLY {len(chunk)} numbered lines in this format:
1. <translated text>
2. <translated text>
...
"""


# ---------------------------------------------------------------------------
# Response parsing
# ---------------------------------------------------------------------------
def _extract_block(raw: str, start_tag: str, end_tag: str) -> Optional[str]:
    match = re.search(re.escape(start_tag) + r"(.*?)" + re.escape(end_tag), raw, re.DOTALL)
    return match.group(1).strip() if match else None


def _clean_translated_line(line_text: str, speaker: Optional[str] = None) -> str:
    """Strip an accidentally echoed speaker tag for THIS line's known speaker
    only (e.g. "[Satya] ...", "Satya: ...", "Satya, ...").

    Deliberately does NOT strip an arbitrary leading "word:"/"word,"/"word-" —
    a generic pattern like that also matches real sentence content that
    happens to start with a name (e.g. translating "Abubhai se bolna ..." as
    "Abubhai, please bring ..." — "Abubhai," here is part of the sentence,
    not an echoed speaker tag, and must be kept).
    """
    cleaned = line_text.strip()
    if speaker:
        pattern = re.escape(speaker)
        cleaned = re.sub(rf"^\[{pattern}\]:?\s*", "", cleaned, flags=re.IGNORECASE).strip()
        cleaned = re.sub(rf"^{pattern}\s*[:,-]\s*", "", cleaned, flags=re.IGNORECASE).strip()
    return cleaned


def _parse_numbered_lines(
    block: str, expected_count: int, speakers: Optional[List[str]] = None
) -> Optional[List[str]]:
    lines: Dict[int, str] = {}
    for line in block.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        # Support formats like "1. ", "1) ", "1: "
        match = re.match(r"^(\d+)[\.\)\:]\s*(.*)$", line)
        if match:
            idx = int(match.group(1))
            speaker = speakers[idx - 1] if speakers and 1 <= idx <= len(speakers) else None
            content = _clean_translated_line(match.group(2).strip(), speaker=speaker)
            if content:
                lines[idx] = content

    if len(lines) >= expected_count:
        return [lines[i] for i in range(1, expected_count + 1)]
    elif len(lines) > 0:
        # If model slightly misnumbered, return in order
        sorted_keys = sorted(lines.keys())
        if len(sorted_keys) >= expected_count:
            return [lines[k] for k in sorted_keys[:expected_count]]

    return None


def _parse_glossary(block: str) -> Dict[str, str]:
    entries = {}
    if not block:
        return entries
    for line in block.strip().splitlines():
        line = line.strip()
        if "=" not in line:
            continue
        src, _, tgt = line.partition("=")
        src, tgt = src.strip(), tgt.strip()
        if src and tgt:
            entries[src] = tgt
    return entries


def parse_response(
    raw: str, expected_count: int, speakers: Optional[List[str]] = None
) -> Tuple[Optional[List[str]], Dict[str, str]]:
    # 1. Try extracting from [TRANSLATION] tags if present
    translation_block = _extract_block(raw, TRANSLATION_START, TRANSLATION_END)
    if not translation_block:
        # Fallback: model returned numbered lines directly
        translation_block = raw

    translated_texts = _parse_numbered_lines(translation_block, expected_count, speakers=speakers)

    glossary_block = _extract_block(raw, GLOSSARY_START, GLOSSARY_END)
    new_glossary = _parse_glossary(glossary_block) if glossary_block else {}

    return translated_texts, new_glossary


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------
def translate_transcript(
    segments: List[SpeakerTranscriptSegment],
    translate_fn: Callable[[str], str],  # your local model call: prompt -> raw text response
    target_language: str,
    max_input_tokens_per_chunk: int = 1500,
    token_estimator: Callable[[str], int] = estimate_tokens,
    translation_rules: Optional[List[str]] = None,  # standing style/policy rules, applied to every chunk
    on_chunk_completed: Optional[Callable[[int, int, List[SpeakerTranscriptSegment]], None]] = None,
) -> Tuple[List[SpeakerTranscriptSegment], TranslationMemory, List[int]]:
    """
    Translates a full transcript across as many model calls as needed,
    carrying a bounded TranslationMemory (glossary + current topic +
    standing rules + recent speaker-attributed sentence pairs) between
    calls, and keeping chunk boundaries on speaker-turn edges wherever the
    token budget allows.

    Timestamps and speaker labels are untouched — only `text` changes.

    A single chunk failing (translate_fn raises, e.g. on an LLM timeout, or
    the response can't be parsed) does not abort the rest of the transcript:
    that chunk's original text is kept as a visible fallback, its 1-based
    chunk number is recorded in the returned failed-chunk list, and the loop
    continues with the next chunk.
    """
    memory = TranslationMemory(translation_rules=translation_rules or [])
    chunks = chunk_segments(segments, max_input_tokens_per_chunk, token_estimator)
    result: List[SpeakerTranscriptSegment] = []
    failed_chunks: List[int] = []

    total_chunks = len(chunks)
    for idx, chunk in enumerate(chunks):
        prompt = build_prompt(chunk, memory, target_language)

        try:
            raw_response = translate_fn(prompt)
            translated_texts, new_glossary = parse_response(
                raw_response, expected_count=len(chunk), speakers=[seg.speaker for seg in chunk]
            )
        except Exception as exc:
            logger.warning("Chunk %d/%d translation call failed (%s); keeping source text for this chunk.",
                           idx + 1, total_chunks, exc)
            translated_texts, new_glossary = None, {}

        if translated_texts is None:
            # Safety net: don't misalign timestamps/speakers by guessing
            # a split. Leave this chunk's source text as-is so it's
            # visibly untranslated (easy to spot/retry).
            translated_texts = [seg.text for seg in chunk]
            failed_chunks.append(idx + 1)

        new_pairs = [
            (seg.speaker, seg.text, t) for seg, t in zip(chunk, translated_texts)
        ]
        memory.update(new_glossary, new_pairs)

        chunk_result = []
        for seg, translated_text in zip(chunk, translated_texts):
            translated_seg = replace(seg, text=translated_text)
            result.append(translated_seg)
            chunk_result.append(translated_seg)

        if on_chunk_completed:
            on_chunk_completed(idx + 1, total_chunks, chunk_result)

    return result, memory, failed_chunks
